name: Verify build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Lint
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        ruby-version: [2.5, 2.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Run tests
        run: bundle exec rake test

